# Generated by Django 4.2.7 on 2023-12-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Eid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100, unique=True)),
                ('Esal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=100)),
                ('Dno', models.IntegerField()),
                ('Dloc', models.CharField(max_length=100)),
                ('Eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
